### PR TITLE
Appendable data

### PR DESCRIPTION
**Pull request by ustulation**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/rfcs/167)

### CODE REVIEW

**Comment by Viv-Rajkumar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[text/0000-appendable-data/0000-appendable-data.md, line 22 \[r1\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQ10fEW_cDEvWbsE5vg:-KQ10fEW_cDEvWbsE5vh:b-hlppb9) ([raw file](https://github.com/maidsafe/rfcs/blob/9b18f9dfd9bf8de3be792a8e7b0258dd2888abaf/text/0000-appendable-data/0000-appendable-data.md#L22)):*
> ```Markdown
>     name        : XorName,
>     version     : u64,
>     owners      : Vec<sign::PublicKey>,
> ```

maybe worth keeping parts similar to `StructuredData` named similar. like this being [current_owner_keys](https://github.com/maidsafe/routing/blob/master/src/structured_data.rs#L41)

---

*[text/0000-appendable-data/0000-appendable-data.md, line 39 \[r1\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQ14i1lwwcns6BEL7tx:-KQ14i1lwwcns6BEL7ty:blk1fjq) ([raw file](https://github.com/maidsafe/rfcs/blob/9b18f9dfd9bf8de3be792a8e7b0258dd2888abaf/text/0000-appendable-data/0000-appendable-data.md#L39)):*
> ```Markdown
>     deleted_data: HashSet<(box_::PublicKey, Vec<u8>)>,
>     signature   : Signature, // All the above fields
>     data        : HashSet<(box_::PublicKey, Vec<u8>)>, // Unsigned
> ```

is it possible to have these tuples named, especially the keys being plenty can help identify this is the `msg_pub_key` which can be used just for this message to keep things anonymous, while the key in `AppendedData` is the one used to verify the filter checks. When the RFC then lists the Vault impl detail, it can hopefully give a clear picture of whats  required here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/167)*

**Comment by Viv-Rajkumar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[text/0000-appendable-data/0000-appendable-data.md, line 39 \[r1\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQ14i1lwwcns6BEL7tx:-KQ15wkOZ_ecWqONP8Fe:bhdj8ez) ([raw file](https://github.com/maidsafe/rfcs/blob/9b18f9dfd9bf8de3be792a8e7b0258dd2888abaf/text/0000-appendable-data/0000-appendable-data.md#L39)):*
<details><summary><i>Previously, Viv-Rajkumar (Viv Rajkumar) wrote…</i></summary>
> is it possible to have these tuples named, especially the keys being plenty can help identify this is the `msg_pub_key` which can be used just for this message to keep things anonymous, while the key in `AppendedData` is the one used to verify the filter checks. When the RFC then lists the Vault impl detail, it can hopefully give a clear picture of whats  required here.
</details>
EDIT: for PrivAppendableData the sender's key ofc not from `AppendedData` used by vault to validate filter, but the one from the wrapper of `(box_::PublicKey, Vec<u8>)` but yeh just looking to see if these things can be named.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/167)*

**Comment by ustulation** [comment]
*[text/0000-appendable-data/0000-appendable-data.md, line 39 \[r1\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQ14i1lwwcns6BEL7tx:-KQ17R-b_xEYpxD1xejk:b-ujy851) ([raw file](https://github.com/maidsafe/rfcs/blob/9b18f9dfd9bf8de3be792a8e7b0258dd2888abaf/text/0000-appendable-data/0000-appendable-data.md#L39)):*
<details><summary><i>Previously, Viv-Rajkumar (Viv Rajkumar) wrote…</i></summary>
> EDIT: for PrivAppendableData the sender's key ofc not from `AppendedData` used by vault to validate filter, but the one from the wrapper of `(box_::PublicKey, Vec<u8>)` but yeh just looking to see if these things can be named.
</details>
There is no way to name in tuples, unless we separate them into structs. Anyway, keys used to verify filter/ownership etc are always `sign::PublicKey`s and the ones to encrypt are always `box_::` ones. I have listed a new interface in Alternatives section that does not have type-erasure like this so more apparent. There things are named so we can do better in that case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/167)*

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[text/0000-appendable-data/0000-appendable-data.md, line 39 \[r1\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQ14i1lwwcns6BEL7tx:-KQ18ejKnkcTVcbiTwwx:by4tf3r) ([raw file](https://github.com/maidsafe/rfcs/blob/9b18f9dfd9bf8de3be792a8e7b0258dd2888abaf/text/0000-appendable-data/0000-appendable-data.md#L39)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> There is no way to name in tuples, unless we separate them into structs. Anyway, keys used to verify filter/ownership etc are always `sign::PublicKey`s and the ones to encrypt are always `box_::` ones. I have listed a new interface in Alternatives section that does not have type-erasure like this so more apparent. There things are named so we can do better in that case.
</details>
There is a train of thought that goes against tuples for API methods and perhaps structs are more API like in that they are specific? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/167)*

**Comment by ustulation** [comment]
*[text/0000-appendable-data/0000-appendable-data.md, line 22 \[r1\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQ10fEW_cDEvWbsE5vg:-KQ19deIZSL3mG6g2mZe:b-896fix) ([raw file](https://github.com/maidsafe/rfcs/blob/9b18f9dfd9bf8de3be792a8e7b0258dd2888abaf/text/0000-appendable-data/0000-appendable-data.md#L22)):*
<details><summary><i>Previously, Viv-Rajkumar (Viv Rajkumar) wrote…</i></summary>
> maybe worth keeping parts similar to `StructuredData` named similar. like this being [current_owner_keys](https://github.com/maidsafe/routing/blob/master/src/structured_data.rs#L41)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/167)*

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[text/0000-appendable-data/0000-appendable-data.md, line 14 \[r5\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQ1EL-eFPwVshM9O64T:-KQ1EL-eFPwVshM9O64U:bbkyemw) ([raw file](https://github.com/maidsafe/rfcs/blob/275594cd9672207c29eb28317ba3043d7d5b90b7/text/0000-appendable-data/0000-appendable-data.md#L14)):*
> `StructuredData` can only 
`StructuredData` MAY only 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/167)*

**Comment by Viv-Rajkumar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[text/0000-appendable-data/0000-appendable-data.md, line 39 \[r1\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQ14i1lwwcns6BEL7tx:-KQ1F2fh5QfH1XKBfQM4:b-crlge) ([raw file](https://github.com/maidsafe/rfcs/blob/9b18f9dfd9bf8de3be792a8e7b0258dd2888abaf/text/0000-appendable-data/0000-appendable-data.md#L39)):*
<details><summary><i>Previously, dirvine (David Irvine) wrote…</i></summary>
> There is a train of thought that goes against tuples for API methods and perhaps structs are more API like in that they are specific? 
</details>
@dirvine :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/167)*

**Comment by afck** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[text/0000-appendable-data/0000-appendable-data.md, line 60 \[r6\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQ5HXugPTMr_b4_W8C2:-KQ5HXugPTMr_b4_W8C3:b-ylq31g) ([raw file](https://github.com/maidsafe/rfcs/blob/f550cd16c4095e0a174f2e2894c50832010b96ff/text/0000-appendable-data/0000-appendable-data.md#L60)):*
> ```Markdown
> - As shown, all fields apart from `data` are only owner modifiable and need to be signed by the owner(s). `data` however will be unsigned and must be modifiable by anyone who passes the `filter` criteria set by owner(s). Owner(s) can set `filter` to either blacklist or whitelist. In case it is set to `FilterType::BlackList`, the vaults shall enforce the rule of allowing everyone but the blacklisted keys to add to `data` on subsequent updates following the change to `filter`, i.e. existing data in `data` field will not be dealt by the vaults. Similarly, if set to `FilterType::WhiteList`, no one but the the whitelisted keys will be allowed to add data.
> - Simultaneous updates of `data` will be dealt with by a merge operation at the vaults. For e.g. if `data` was originally empty and 3 updates from 3 different sources arrived simultaneously, then vaults would do a union operation, and the resultant appendable data would have all three updates.
> - Deletion of data is done by moving the particular data in `data` field to `deleted_data` by the owner followed by the `POST` of the entire `PubAppendableData`/`PrivAppendableData`. As with any owner related modifications via `POST`, the vaults shall in this case assert the version increment. It is important to delete in this manner otherwise churn can bring back the deleted data in some cases. When data is moved from `data` to `delete_data`, vaults will ensure that any merge operation that tries to put data back into `data` while it also resides in `deleted_data` shall be ignored. Emptying `deleted_data` itself can be done by the user by similar `POST` after some period of time which though is unspecified, but should be safe in excess of 20 min or so (in case it's a heavily churning network at that point of time).
> ```

Can a piece of data only be deleted by the one who created it or by anyone who also has permissions to add data?

---

*[text/0000-appendable-data/0000-appendable-data.md, line 108 \[r6\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQ5G6i76VBRL4MPtsgo:-KQ5G6i8BNC2HZ_2MSY2:b-qlz26m) ([raw file](https://github.com/maidsafe/rfcs/blob/f550cd16c4095e0a174f2e2894c50832010b96ff/text/0000-appendable-data/0000-appendable-data.md#L108)):*
> ```Markdown
> - There is currently no _push_ mechanism for the append operation, i.e. the owner must resort to polling (as opposed to notifications) to check if `Priv/PubAppendableData` has been updated.
> - Type erasure into `Vec<u8>` for `PrivAppendableData` and reconstruction at vaults via specific parsing logic might not be ideal way to approach this.
> - There is no way for owner to actually blacklist a spammer in case of `PrivAppendableData`. This is because the outer shell which is discarded by the vaults after verification contains the `sign::PublicKey` which the vaults actually use for filter checks. However what owner sees as `sign::PublicKey` after decrypting the data might not be the same and if owner blacklists this key, there isn't anything that is going to happen because it's the outer key that was malacious. The vaults discard this outer shell for the sake of anonymity preservation (i.e. do not want sender to be traceable).
> ```

Is the `BlackList` option useful at all then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/167)*

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[text/0000-appendable-data/0000-appendable-data.md, line 108 \[r6\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQ5G6i76VBRL4MPtsgo:-KQ5IbHlNt88bKCbDAUi:b-vzw871) ([raw file](https://github.com/maidsafe/rfcs/blob/f550cd16c4095e0a174f2e2894c50832010b96ff/text/0000-appendable-data/0000-appendable-data.md#L108)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Is the `BlackList` option useful at all then?
</details>
Perhaps, arguably not, although does still make well known mass follower type accounts perhaps more difficult to spam somebody? Basically it's a deterrent as in today's web where you can create multiple accounts to get around a blacklist  I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/167)*

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[text/0000-appendable-data/0000-appendable-data.md, line 60 \[r6\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQ5HXugPTMr_b4_W8C2:-KQ5N8CondUQWM4gbyjC:b-2gpsik) ([raw file](https://github.com/maidsafe/rfcs/blob/f550cd16c4095e0a174f2e2894c50832010b96ff/text/0000-appendable-data/0000-appendable-data.md#L60)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Can a piece of data only be deleted by the one who created it or by anyone who also has permissions to add data?
</details>
The owner could specify the data has to be immutable or a certain type for parsing, so this becomes app specific really. Could point to immutable (cannot be deleted) or SD can be edited / deleted) or similar. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/167)*

**Comment by Viv-Rajkumar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[text/0000-appendable-data/0000-appendable-data.md, line 60 \[r6\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQ5HXugPTMr_b4_W8C2:-KQ5NnhqJcs37Z_HVGbY:b-76866l) ([raw file](https://github.com/maidsafe/rfcs/blob/f550cd16c4095e0a174f2e2894c50832010b96ff/text/0000-appendable-data/0000-appendable-data.md#L60)):*
<details><summary><i>Previously, dirvine (David Irvine) wrote…</i></summary>
> The owner could specify the data has to be immutable or a certain type for parsing, so this becomes app specific really. Could point to immutable (cannot be deleted) or SD can be edited / deleted) or similar. 
</details>
Well by "Delete" if you mean removing it from `AppendableData.data`, then yes its limited to the owner/owners of the same `AppendableData` not the user who appended the info.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/167)*

**Comment by afck** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[text/0000-appendable-data/0000-appendable-data.md, line 60 \[r6\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQ5HXugPTMr_b4_W8C2:-KQ5XJZh7kQkIn56_-b0:b-8fx2u7) ([raw file](https://github.com/maidsafe/rfcs/blob/f550cd16c4095e0a174f2e2894c50832010b96ff/text/0000-appendable-data/0000-appendable-data.md#L60)):*
<details><summary><i>Previously, Viv-Rajkumar (Viv Rajkumar) wrote…</i></summary>
> Well by "Delete" if you mean removing it from `AppendableData.data`, then yes its limited to the owner/owners of the same `AppendableData` not the user who appended the info.
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/167)*

**Comment by maqi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[text/0000-appendable-data/0000-appendable-data.md, line 22 \[r7\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQLBXnLgqIjQIXEI0ER:-KQLBXnLgqIjQIXEI0ES:b-5wqt2o) ([raw file](https://github.com/maidsafe/rfcs/blob/058b3856fcf519e0188da0e534bc92670f173372/text/0000-appendable-data/0000-appendable-data.md#L22)):*
> ```Markdown
>     name                     : XorName,
>     version                  : u64,
>     current_owner_keys       : Vec<sign::PublicKey>,
> ```

Is`owner` of the data shall only be one, and others to be `publisher` or `participant` ?
Also, the current `current/previous owner` indicates the ownership can be transferred.

---

*[text/0000-appendable-data/0000-appendable-data.md, line 26 \[r7\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQLAsLz6Uys6K_f-Y-L:-KQLAsM-beEp7JXXY7Yn:brudu2l) ([raw file](https://github.com/maidsafe/rfcs/blob/058b3856fcf519e0188da0e534bc92670f173372/text/0000-appendable-data/0000-appendable-data.md#L26)):*
> previous_owner_signatures
how this has been populated and what is it for?
if this relates to `data pushed`, `vec` requires a fixed order of both, then what happen when `delete data`?

---

*[text/0000-appendable-data/0000-appendable-data.md, line 78 \[r7\]](https://reviewable.io:443/reviews/maidsafe/rfcs/167#-KQLCdv3wZohNRMjv7Fw:-KQLCdv4nvW4dnOXIiJF:bu944m0) ([raw file](https://github.com/maidsafe/rfcs/blob/058b3856fcf519e0188da0e534bc92670f173372/text/0000-appendable-data/0000-appendable-data.md#L78)):*
> ```Markdown
> - Both `PubAppendableData` and `PrivAppendableData` shall have max size restriction of **100 KiB**.
> - `AppendedData` contains the location (pointer) of the actual data which can be any type (`Immutable`, `Structured`, etc.) as identified by `DataIdentifier`. The pointer mechanism will keep appended data small as it only contains a pointer to the actual data which could be colossal and fill entire 100 KiB limit by just itself.
> - As shown, all fields of `Pub/PrivAppendableData` apart from `Pub/PrivAppendableData::data` are only owner modifiable and need to be signed by the owner(s). `Pub/PrivAppendableData::data` however will be unsigned and shall be modifiable by anyone who passes the `filter` criteria set by owner(s). Owner(s) can set `filter` to either blacklist or whitelist. In case it is set to `FilterType::BlackList`, the vaults shall enforce the rule of allowing everyone but the blacklisted keys to add to `data` on subsequent updates following the change to `filter`, i.e. existing data in `data` field will not be dealt by the vaults. Similarly, if set to `FilterType::WhiteList`, no one but the the whitelisted keys will be allowed to add data.
> ```

i guess this `changing` list feature requires some additional API? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/167)*

**Pull request merged**
