### PR TITLE
Direct Data API in Launcher

### PR DESCRIPTION
**Pull request by cretz**
Rendered: https://github.com/cretz/rfcs/blob/launcher-direct-data-api/proposed/0000-launcher-direct-data-api.md

---
This change is [Review on Reviewable](https://reviewable.io/reviews/maidsafe/rfcs/100)

### CODE REVIEW

**Comment by cretz** [comment]
Note I am beginning to second guess myself on whether this should be encrypted from launcher to app like everything else. That possibly introduces unnecessary overhead (since it's all localhost anyways).

**Comment by rossmuir** [comment]
Thank you for the RFC PR, sorry no-one has had an opportunity to review / comment on this yet - all hands are on getting the MVP out. Hopefully folks will be freed up to have a look very soon - thanks again.

**Comment by cretz** [comment]
No prob. And I am willing to revise it as necessary if/when the launcher API changes to maintain consistency.

**Comment by dirvine** [comment]
@rossmuir Can we get an issue number here please. (thx)

**Comment by rossmuir** [comment]
@dirvine > https://github.com/maidsafe/rfcs/issues/109

**Pull request merged**
