### PR TITLE
Node age

### PR DESCRIPTION
**Pull request by dirvine**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/rfcs/194)

### CODE REVIEW

**Comment by maqi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[text/0045-node-age/0045-node-age.md, line 25 at r1](https://reviewable.io:443/reviews/maidsafe/rfcs/194#-KT1SuBBtDhqk1zld6Le:-KT1SuBCSKFU0LcSY5_M:bctfnvk) ([raw file](https://github.com/maidsafe/rfcs/blob/9661ce547a5606c116f9127802dcfd5ebe53b9b2/text/0045-node-age/0045-node-age.md#L25)):*
> ```Markdown
> ## Motivation
> 
> The network must secure against targeting groups. Earlier RFC's have solutions for group security,
> ```

shall correspondent RFC to be linked?

---

*[text/0045-node-age/0045-node-age.md, line 42 at r1](https://reviewable.io:443/reviews/maidsafe/rfcs/194#-KT1SlDJyYXX0tTw50uq:-KT1SlDJyYXX0tTw50ur:b-9slcv7) ([raw file](https://github.com/maidsafe/rfcs/blob/9661ce547a5606c116f9127802dcfd5ebe53b9b2/text/0045-node-age/0045-node-age.md#L42)):*
> ```Markdown
> This RFC requires that nodes that are not "well behaved" will be excluded from the network.
> Additionally it is assumed that data chains are
> [implemented](https://github.com/maidsafe/rfcs/blob/master/text/0029-data-chains.md/0029-data-chains.md) and
> ```

shall `data chains` be linked instead of `implemented` ?

---

*[text/0045-node-age/0045-node-age.md, line 50 at r1](https://reviewable.io:443/reviews/maidsafe/rfcs/194#-KT1T7fXJ2t8Rwme02xM:-KT1T7fYrd5x06rOtfur:b-ddwnsz) ([raw file](https://github.com/maidsafe/rfcs/blob/9661ce547a5606c116f9127802dcfd5ebe53b9b2/text/0045-node-age/0045-node-age.md#L50)):*
> ```Markdown
>     considered invalid nodes).
>   - Groups will ***not** accept connections from the same IP address.
>   - Groups will only allow 1, node with 0 age.
> ```

`only allow ` node with 0 age`

---

*[text/0045-node-age/0045-node-age.md, line 67 at r1](https://reviewable.io:443/reviews/maidsafe/rfcs/194#-KT1TyBh7ktGqPJuZKoI:-KT1TyBh7ktGqPJuZKoJ:bvm1dq7) ([raw file](https://github.com/maidsafe/rfcs/blob/9661ce547a5606c116f9127802dcfd5ebe53b9b2/text/0045-node-age/0045-node-age.md#L67)):*
> ```Markdown
> 
> Without any node relocation an attacker with a single join will enter a group and therefore requires
> (Q - 1) nodes To take over the group completely. An attacker will therefore require the attacker try
> ```

`An attack will ... ` ?

---

*[text/0045-node-age/0045-node-age.md, line 176 at r1](https://reviewable.io:443/reviews/maidsafe/rfcs/194#-KT1Wc_goSBCa9exMITk:-KT1Wc_goSBCa9exMITl:b-2qyuav) ([raw file](https://github.com/maidsafe/rfcs/blob/9661ce547a5606c116f9127802dcfd5ebe53b9b2/text/0045-node-age/0045-node-age.md#L176)):*
> ```Markdown
> connecting to each group member the node must supply the `JoiningProof` as described above. AS there
> is no history for this node it will be allocated an age == zero. This means the node itself on
> successful join will be immediately relocated.
> ```

So an attacker have a node behaving well for some time and gained Age 5 in group T
Then, he can just start up nodes quickly and test whether has been relocated to the target group T.
The relocating will happen immediately so such test won't take much time.
This will give the attacker at least two Age 1 nodes (Age 1 allows two churn events).
Plus the previous Age 5 node, the attacker now controls three nodes, which gives him a high chance to corrupt the group.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/194)*

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[text/0045-node-age/0045-node-age.md, line 25 at r1](https://reviewable.io:443/reviews/maidsafe/rfcs/194#-KT1SuBBtDhqk1zld6Le:-KT1YbZd_2QOySJR_ulP:b-gtmvy3) ([raw file](https://github.com/maidsafe/rfcs/blob/9661ce547a5606c116f9127802dcfd5ebe53b9b2/text/0045-node-age/0045-node-age.md#L25)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> shall correspondent RFC to be linked?
</details>
Good point I will do that. 

---

*[text/0045-node-age/0045-node-age.md, line 42 at r1](https://reviewable.io:443/reviews/maidsafe/rfcs/194#-KT1SlDJyYXX0tTw50uq:-KT1Yg4s-uJFo90g9Sm9:b-85oi0l) ([raw file](https://github.com/maidsafe/rfcs/blob/9661ce547a5606c116f9127802dcfd5ebe53b9b2/text/0045-node-age/0045-node-age.md#L42)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> shall `data chains` be linked instead of `implemented` ?
</details>
They will be linked as they are a separate crate. There will be a degree of impl in routing and vaults still mind you. 

---

*[text/0045-node-age/0045-node-age.md, line 67 at r1](https://reviewable.io:443/reviews/maidsafe/rfcs/194#-KT1TyBh7ktGqPJuZKoI:-KT1ZuC77gM-WJzvbQlr:b-vpfr4s) ([raw file](https://github.com/maidsafe/rfcs/blob/9661ce547a5606c116f9127802dcfd5ebe53b9b2/text/0045-node-age/0045-node-age.md#L67)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> `An attack will ... ` ?
</details>
FYI - done

---

*[text/0045-node-age/0045-node-age.md, line 176 at r1](https://reviewable.io:443/reviews/maidsafe/rfcs/194#-KT1Wc_goSBCa9exMITk:-KT1_JKL-xjIrHh2MHTu:b-wghj4s) ([raw file](https://github.com/maidsafe/rfcs/blob/9661ce547a5606c116f9127802dcfd5ebe53b9b2/text/0045-node-age/0045-node-age.md#L176)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> So an attacker have a node behaving well for some time and gained Age 5 in group T
> Then, he can just start up nodes quickly and test whether has been relocated to the target group T.
> The relocating will happen immediately so such test won't take much time.
> This will give the attacker at least two Age 1 nodes (Age 1 allows two churn events).
> Plus the previous Age 5 node, the attacker now controls three nodes, which gives him a high chance to corrupt the group.
</details>
Agreed, but those nodes will not be there long, 1 will create a churn so they may exist for 1 churn event, but importantly with almost no rank in a vote. This is where we need to consider carefully the quorum algorithm to decide on when the vote weight starts (i.e. above median etc.) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/194)*

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[text/0045-node-age/0045-node-age.md, line 25 at r1](https://reviewable.io:443/reviews/maidsafe/rfcs/194#-KT1SuBBtDhqk1zld6Le:-KT1aX5q59fQ00Jk97ks:b-896fix) ([raw file](https://github.com/maidsafe/rfcs/blob/9661ce547a5606c116f9127802dcfd5ebe53b9b2/text/0045-node-age/0045-node-age.md#L25)):*
<details><summary><i>Previously, dirvine (David Irvine) wrote…</i></summary>
> Good point I will do that. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/194)*

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[text/0045-node-age/0045-node-age.md, line 50 at r1](https://reviewable.io:443/reviews/maidsafe/rfcs/194#-KT1T7fXJ2t8Rwme02xM:-KT1aeyymUYj5kzslcAO:b-896fix) ([raw file](https://github.com/maidsafe/rfcs/blob/9661ce547a5606c116f9127802dcfd5ebe53b9b2/text/0045-node-age/0045-node-age.md#L50)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> `only allow ` node with 0 age`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/194)*

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[text/0045-node-age/0045-node-age.md, line 67 at r1](https://reviewable.io:443/reviews/maidsafe/rfcs/194#-KT1TyBh7ktGqPJuZKoI:-KT1ah_9D9OpPfNYIHUB:b-896fix) ([raw file](https://github.com/maidsafe/rfcs/blob/9661ce547a5606c116f9127802dcfd5ebe53b9b2/text/0045-node-age/0045-node-age.md#L67)):*
<details><summary><i>Previously, dirvine (David Irvine) wrote…</i></summary>
> FYI - done
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/194)*

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[text/0045-node-age/0045-node-age.md, line 176 at r1](https://reviewable.io:443/reviews/maidsafe/rfcs/194#-KT1Wc_goSBCa9exMITk:-KT1eCXysp3H108uZiUa:bsa20e8) ([raw file](https://github.com/maidsafe/rfcs/blob/9661ce547a5606c116f9127802dcfd5ebe53b9b2/text/0045-node-age/0045-node-age.md#L176)):*
<details><summary><i>Previously, dirvine (David Irvine) wrote…</i></summary>
> Agreed, but those nodes will not be there long, 1 will create a churn so they may exist for 1 churn event, but importantly with almost no rank in a vote. This is where we need to consider carefully the quorum algorithm to decide on when the vote weight starts (i.e. above median etc.) 
</details>
We also must consider there will only ever be 1 noe per group max waiting to connect. All others will be rejected in that time. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rfcs/194)*

**Pull request merged**
